Brainzzler/Brainzzler/Controllers/TestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Brainzzler.Models;
using Microsoft.AspNetCore.Authorization;

namespace Brainzzler.Controllers
{
    /// <summary>
    /// this controller is responsible for the tests
    /// </summary>
    [Authorize]
    public class TestsController : Controller
    {
        private readonly Brainzzler_DBContext _context;

        /// <summary>
        /// Initializes the context
        /// </summary>
        /// <param name="context"></param>
        public TestsController(Brainzzler_DBContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Returns all tests in the DB
        /// </summary>
        /// <returns>GET: Tests</returns>
        public IActionResult Index()
        {
            return View(_context.Tests.ToList());
        }

        /// <summary>
        /// Returns the test on the given id
        /// Checks if the test exists,
        /// if it does, it takes it from the DB and loads all the questions and answers from the test
        /// </summary>
        /// <param name="id"></param>
        /// <returns>/Tests/Details/{id}</returns>
        public async Task<IActionResult> Details(long id)
        {
            if (TestExists(id))
            {
                var test = await _context.Tests
                .FirstOrDefaultAsync(m => m.Id == id);

                await _context.Entry(test).Collection(e => e.Questions).LoadAsync();
                foreach (var question in test.Questions)
                {
                    await _context.Entry(question).Collection(e => e.Answers).LoadAsync();
                }
                return View(test);
            }
            else
            {
                return NotFound();
            }
        }

        /// <summary>
        /// Returns view
        /// </summary>
        /// <returns>GET: Tests/Create</returns>
        public IActionResult Create()
        {
            return View("Create");
        }

        /// <summary>
        /// Creates test and saves changes
        /// </summary>
        /// <param name="test"></param>
        /// <returns>POST: Tests/Create</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Test_Name")] Test test)
        {
            if (ModelState.IsValid)
            {
                _context.Add(test);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(test);
        }

        /// <summary>
        /// finds test by ID and returns it for future use
        /// </summary>
        /// <param name="id"></param>
        /// <returns>GET: Tests/Edit/5</returns>
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests.FindAsync(id);
            if (test == null)
            {
                return NotFound();
            }
            return View(test);
        }

        /// <summary>
        /// Updates test and saves it to DB;
        /// </summary>
        /// <param name="id"></param>
        /// <param name="test"></param>
        /// <returns>POST: Tests/Edit/5</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Test_Name")] Test test)
        {
            if (id != test.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(test);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestExists(test.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(test);
        }

        /// <summary>
        /// finds test in DB and returns it to the view for DeleteConfirmed
        /// </summary>
        /// <param name="id"></param>
        /// <returns>GET: Tests/Delete/5</returns>
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var test = await _context.Tests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (test == null)
            {
                return NotFound();
            }

            return View(test);
        }

        /// <summary>
        /// Deletes test from DB and saves changes
        /// </summary>
        /// <param name="id"></param>
        /// <returns>POST: Tests/Delete/5</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var test = await _context.Tests.FindAsync(id);
            _context.Tests.Remove(test);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Checks if the test exists in the DB
        /// </summary>
        /// <param name="id"></param>
        /// <returns>true or false</returns>
        private bool TestExists(long id)
        {
            return _context.Tests.Any(e => e.Id == id);
        }
    }
}

Brainzzler/Brainzzler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="google-site-verification" content="8MSOH_iCXQRjcxw73FoKpeDde1NLOC7IkUMvpF6uITY" />
    <meta name="description" content="Brainzzler e образователна игра целяща да мотивира децата да учат в ИТ-сферата.">
    <title>@ViewData["Title"] - Brainzzler</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>

    @if (ViewData["Title"] == "Games")
    {
        <link rel="stylesheet" href="~/css/games.css" />
    }
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @if (ViewData["Title"] == "Начало")
    {
        <div class="jumbotron banner text-center" style=" background-image: url(../images/header_home.png);margin-bottom:0;">
            <div style="vertical-align: middle; display: inline-block;">
                <img class="img-fluid" src="images\logo.png" alt="logo">
            </div>
            <div style="vertical-align: middle; display: inline-block; text-align: left; margin-left: 10px;">
                <h1>Brainzzler </h1>
                <h2>Забавлявай се, докато учиш!</h2>
            </div>
        </div>
    }

    <header class="sticky-top">
        <nav class="sticky-top navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid sticky-top">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Brainzzler</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Начало</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Tests" asp-action="Index">Въпроси</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Games" asp-action="Index">Игри</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom: 30px">
        @* <partial name="_CookieConsentPartial" />*@
        <main role="main" class="pb-3" style="margin-top: 50px; margin-bottom: 100px;">
            @RenderBody()
        </main>
    </div>

    <footer class="footer" id="footer_layout">
        <p>
            &copy; 2019 - Brainzzler
            - GNU license - Разработен за Национална олимпиада по Информационни технологии - 
            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </p>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/quizz.js" asp-append-version="true"></script>
    @if (ViewData["Title"] == "Games")
    {
        <script src="~/js/games.js"></script>
    }
    @RenderSection("Scripts", required: false)
</body>
</html>

Brainzzler/Brainzzler/Views/Shared/_LayoutLR.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="google-site-verification" content="8MSOH_iCXQRjcxw73FoKpeDde1NLOC7IkUMvpF6uITY" />
    <title>@ViewData["Title"] - Brainzzler</title>
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/logiRegisterBG.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="bg-all">
        <div class="jumbotron banner text-center" style="background: none;">
            <div style="vertical-align: middle; display: inline-block;">
                <a href="/">
                    <img class="img-fluid" src="~/images/logo.png" alt="bacground-image">
                </a>
            </div>
            <div style="vertical-align: middle; display: inline-block; text-align: left; margin-left: 10px;">
                <h1>Brainzzler</h1>
            </div>
        </div>
        <div class="container" style="background-color: white; margin-top:-30px; margin-bottom: 30px; padding: 40px">
            <div class="text-center">
                <h3>
                    <a class="link" asp-area="Identity" asp-page="/Account/Login">Вход за потребители</a>
                    &nbsp;|&nbsp;
                    <a class="link" asp-area="Identity" asp-page="/Account/Register">Регистрация</a>
                </h3>
            </div>
            <div class="container text-center">
                <partial name="_CookieConsentPartial" />
                <main role="main" class="pb-3 text-center" style="margin: 50px;">
                    @RenderBody()
                </main>
            </div>
        </div>
        <br>
    </div>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>